<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="footer-logo">
	<?php if($block->getGeneralConfig() == 1) : ?>
		<img src="<?php echo $block->getLogoConfig(); ?>" alt="<?= $block->getLogoAlt() ?>"  <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?> class="img-responsive">
	<?php endif; ?>	
</div>